### PR TITLE
Fixed error while unparsing consecutive entities

### PR DESCRIPTION
**Pull request by Princic-1837592**
As shown here https://github.com/pyrogram/pyrogram/issues/870
Now sorting also takes in consideration the original order of the entities

### CODE REVIEW

**Comment by delivrance** [comment]
I found that a much simpler solution would be using `entities_offsets.reverse()` or iterate directly in reverse order instead of an intricate composition of `map/sorted/enumerate` as entities are already coming sorted as wanted from the server. The code just needs the reverse.

**Comment by Princic-1837592** [comment]
But we only need to reverse entities with same offset, not the entire list. This is what enumerate is for

**Comment by delivrance** [comment]
What I'm saying is that the code builds the unparsed string from end to start and since entities are already sorted by the server we simply need to iterate through `reversed(entities_offsets)` in the loop below.

**Comment by Princic-1837592** [comment]
You are right. So the "problem" is the stability of `.sort`

**Comment by delivrance** [comment]
Why closing it? You can edit this PR.

**Comment by Princic-1837592** [comment]
Sorry, I'm not so used to github

**Comment by delivrance** [comment]
You should create one branch per PR. I see you included other changes in this one.

**Comment by Princic-1837592** [comment]
I wanted to add a commit to this PR https://github.com/pyrogram/pyrogram/pull/712 but the commit was automatically added to this one. Maybe the other one is too old

**Comment by delivrance** [comment]
Either cleanup your master branch to include only the relevant changes or create a new branch, apply changes there and open a new PR.

**Pull request closed without merging**
