### PR TITLE
Improve fstrings

### PR DESCRIPTION
**Pull request by NaytSeyd**

### CODE REVIEW

**Review by jonatan1609 — APPROVED** [review]
cool

**Review by delivrance — CHANGES_REQUESTED** [review]
No. Some lines go beyond 120 characters

**Comment by NaytSeyd** [comment]
> No. Some lines go beyond 120 characters

I've made changes, can you check ?

**Review by delivrance — COMMENTED** [review]
You made it worse. Some lines are short and readable the way they were and not even close to 120 columns, there was no need to split them.

**Pull request closed without merging**
