### PR TITLE
on_error() decorator added

### PR DESCRIPTION
**Pull request by jonatan1609**
a new on_error decorator has been added.
you can use it via

```
@app.on_error()
def error_handler(client, exception_object):
    pass

```
or

```
@app.on_error(check_all=True)
def error_handler(client, exception_object):
    pass
```

same as 

`app.add_handler(handlers.error_handler.ErrorHandler(app, error_handler, True))`

In order to catch all errors raised on the application, not only RPCErrors.

### CODE REVIEW

**Comment by pokurt** [comment]
this is one of the useless pr ive seen so far but you are damn creative on this

**Comment by Sunda001** [comment]
> this is one of the useless pr ive seen so far but you are damn creative on this

not really useless

**Comment by zeroone2numeral2** [comment]
@pokurt mind motivating why you consider this useless? I honestly see why configuring a callback that should run when one of your handlers raises an exception can be considered a useful feature to have. Maybe it might be considered out of the scope of a library such as pyrogram

@jonatan1609 a cool thing to have would be to tell the dispatcher whether to continue to propagate the update to the following handlers, if the exception is handled by an error handler

**Comment by jonatan1609** [comment]
> @jonatan1609 a cool thing to have would be to tell the dispatcher whether to continue to propagate the update to the following handlers, if the exception is handled by an error handler 


Yup that's cool. I am waiting for @delivrance 's answer what does he think about it, if it will be okay I'll keep developing it and i will add docs as well.

**Comment by jonatan1609** [comment]
Do not merge it yet, i need to fix some bugs.

**Comment by pokurt** [comment]
lmao

**Comment by jonatan1609** [comment]
What’s so fooni

**Pull request closed without merging**
