### PR TITLE
Added missing Attributes for `message.reply_text`

### LINKED ISSUE #925: `message.reply_text` is missing `schedule_date` and `protect_content`.
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

As the pyrogram's `send_message` is having the option for `schedule_date` and `protect_content` but `message.reply_text` is missing that. 

### Steps to reproduce

1. Start a client
2. Try to use `message.reply_text` with `schedule_date` and `protect_content` option.
3. It will generate the error. 

### Code example

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by MrBotDeveloper**
Closes #925

### CODE REVIEW

**Comment by MrBotDeveloper** [comment]
I have removed all previous commits the main commit is [this one](https://github.com/pyrogram/pyrogram/pull/926/commits/0bdcbf922b994a32f33ab7cbc7915686d0d80829)

**Comment by delivrance** [comment]
Messed up PR

**Comment by MrBotDeveloper** [comment]
Messed up ?? I didn't get I don't know why GitHub is showing the files that are same as the current pyrogram's master branch.

**Comment by MrBotDeveloper** [comment]
> Messed up ?? I didn't get I don't know why GitHub is showing the files that are same as the current pyrogram's master branch.

@delivrance

**Comment by MrBotDeveloper** [comment]
You can check it by merging to any other clone branch....

**Pull request closed without merging**
