### PR TITLE
add missing file_ref in set_chat_photo

### PR DESCRIPTION
**Pull request by Sunda001**
fix empty file reference

### CODE REVIEW

**Comment by xsolinsx** [comment]
it should be added also to the shortcut method

**Comment by JosXa** [comment]
This and https://github.com/pyrogram/pyrogram/pull/347 make me think that there might be other places where the argument is missing 🤔

**Comment by alissonlauffer** [comment]
shouldn't this be merged into the develop branch first?

**Comment by delivrance** [comment]
@alissonlauffer you are right, I assumed the PR was pointing to `develop` already

**Comment by delivrance** [comment]
@Sunda001 Could you cherry pick the commit and re-apply to the develop branch of your fork? Then open a new PR

**Comment by Sunda001** [comment]
> @Sunda001 Could you cherry pick the commit and re-apply to the develop branch of your fork? Then open a new PR

sure

**Pull request merged**
