### PR TITLE
Add new methods for bot commands

### PR DESCRIPTION
**Pull request by Mahesh0253**

### CODE REVIEW

**Review by jonatan1609 — APPROVED** [review]
Seems good

**Comment by jonatan1609** [comment]
Popping up 😅🤞

**Comment by jonatan1609** [comment]
> Seems good, works.

**Comment by dhuuthang** [comment]
> Seems good, works

I can confirm, been using this for a while and not a single error so far.

**Comment by Danipulok** [comment]
`raw.functions.bots.SetBotCommands` seems to not be working currently after new version of Bot API.
(It returns `True` even though I don't have any changes on a client side)

@delivrance sorry for pinging, but could you please merge it ASAP?
I hope it would solve the problem.

**Comment by jonatan1609** [comment]
👀

**Pull request closed without merging**
