### PR TITLE
Add RPC Error: CHAT_FORWARDS_RESTRICTED

### LINKED ISSUE #820: Add documentation about `CHAT_FORWARDS_RESTRICTED`
## Checklist
- [X] I believe the idea is awesome and would benefit the library.
- [X] I have searched in the issue tracker for similar requests, including closed ones.

## Description
A detailed description of the request.

Telegram has added a new feature about restrict saving content in groups. We should document it in 400 Bad request section of 'API Errors'

### PR DESCRIPTION
**Pull request by D4v1dH03**
Add the RPC error about some chats restrict forwarding
Fixes #820

### CODE REVIEW

**Comment by New-dev0** [comment]
Isn't it the `CHAT_FORWARDS_RESTRICTED` ? 
**S**

**Comment by D4v1dH03** [comment]
OK Fixed

**Comment by AbirHasan2005** [comment]
Before I got this error as 400 BadRequest but now I get this error as 406 NotAcceptable. Maybe Telegram moved the error from 400 to 406?

**Comment by D4v1dH03** [comment]
It _is_ exactly the following:

```
pyrogram.errors.exceptions.bad_request_400.BadRequest: [400 Bad Request]: [400 CHAT_FORWARDS_RESTRICTED] (caused by "messages.ForwardMessages")
```

I don't see 406

**Pull request merged**
