### PR TITLE
Add support for uploading from file pointers

### PR DESCRIPTION
**Pull request by OctoNezd**
Fixes https://github.com/pyrogram/pyrogram/issues/261
image

All file pointers must have attribute .name

Tested methods:
- [x] send_animated_sticker
- [x] send_animation
- [x] send_audio
- [x] send_document
- [x] send_photo
- [x] send_sticker
- [x] send_video
- [x] send_video_note
- [x] send_voice

### CODE REVIEW

**Comment by OctoNezd** [comment]
Can someone test other methods?

**Comment by AyraHikari** [comment]
All test passed, except for send_voice

`client.send_voice(c, open("voice.ogg", "rb"))`

```
ERROR:pyrogram.client.ext.dispatcher:'str' object has no attribute 'write'
Traceback (most recent call last):
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 178, in update_worker
    handler.callback(self.client, *args)
  File "test.py", line 47, in starting_test
    client.send_voice(c, open("voice.ogg", "rb"))
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/client/methods/messages/send_voice.py", line 161, in send_voice
    **self.parser.parse(caption, parse_mode)
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/client/client.py", line 1087, in send
    r = self.session.send(data, retries, timeout)
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/session/session.py", line 437, in send
    return self._send(data, timeout=timeout)
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/session/session.py", line 403, in _send
    message = self.msg_factory(data)
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/api/core/tl_object.py", line 76, in __len__
    return len(self.write())
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/api/functions/messages/send_media.py", line 104, in write
    b.write(self.media.write())
  File "/home/ayra/.local/share/virtualenvs/test-jenOu_xj/lib/python3.7/site-packages/pyrogram/api/types/input_media_uploaded_document.py", line 84, in write
    b.write(self.file.write())
AttributeError: 'str' object has no attribute 'write'
```

**Comment by OctoNezd** [comment]
I am not sure about why voice is failing, cause I don't see any errors that related to my changes

**Comment by OctoNezd** [comment]
Fixed `send_voice`

**Pull request closed without merging**
