### PR TITLE
Recovering gaps

### PR DESCRIPTION
**Pull request by Tenount**
#263

### CODE REVIEW

**Comment by Legenda24** [comment]
Better to add argument for this ig. (for Client)

**Comment by Tenount** [comment]
> Better to add argument for this ig. (for Client)
> Argument for handle those updates or not

I'm stuck here. Can you implement this?

**Comment by Legenda24** [comment]
> > Better to add argument for this ig. (for Client)
> > Argument for handle those updates or not
> 
> I'm stuck here. Can you implement this?

I wist I could. 😔
Anyway good job, thanks for this, good luck.

**Comment by Tenount** [comment]
@delivrance Please review

**Pull request closed without merging**
