### PR TITLE
fixed memory leak when session.send coroutine is cancelled

### PR DESCRIPTION
**Pull request by YoilyL**
added that when session.send coroutine is cancelled (or any other exception) the result should be removed from the results list

### CODE REVIEW

**Comment by YoilyL** [comment]
I added the second commit for my own repo after creating this pr.. I didn't intend for it to be included.

**Comment by AlissonLauffer** [comment]
> I added the second commit for my own repo after creating this pull requests and didn't intend for it to be included.. I guess github adds it automatically.
> 
> feel free to ignore it (or not)

Yes, gjthub adds automatically. You should create a new branch with the purposed changes for the PR (eg.: create the branch fix-memory-leak, add the related commits and then create the pull request).

You can remove the last commit from the PR by force-pusing your branch.

**Comment by delivrance** [comment]
Discussion for this PR took place at the group, starting from here: https://t.me/PyrogramLounge/118984

**Comment by YoilyL** [comment]
closed in favor of #311

**Pull request closed without merging**
