### PR TITLE
Implement extendable session storage, move to SQLite as main storage (WIP)

### PR DESCRIPTION
**Pull request by bakatrouble**
Tested with both new session and existing one.
Still needs docs...

### CODE REVIEW

**Comment by bakatrouble** [comment]
Previous commit closes #175

**Comment by bakatrouble** [comment]
SQLite storage is not active yet as migration from JSON is not implemented

**Comment by bakatrouble** [comment]
Migration from JSON implemented, SQLite storage is used by default

**Comment by Jeepeo** [comment]
Add Redis too :)

**Comment by delivrance** [comment]
Hi, I'm currently in the process of reviewing and enhancing this PR thoroughly.

**Pull request merged**
